### PR TITLE
HTTP endpoint

### PR DESCRIPTION
**Pull request by shahzaib414**

### CODE REVIEW

**Comment by codernaut** [comment]
please do the changes i agree generated files should not be part of commit

**Comment by wahibhaq** [comment]
I had put some considerable effort to delete all generated files and folders from the origin repo but I can see they are merged again despite complaining.

Was it lack of time or help?

**Comment by wahibhaq** [comment]
I had put some considerable effort to delete all generated files and folders from the origin repo but I can see they are merged again despite complaining.

Was it lack of time or help?

**Comment by codernaut** [comment]
@shahzaib414  me closing this please submit a new request with your latest changes also incorporating @wahibhaq comments

**Comment by codernaut** [comment]
No i didnt merge it i just closed it

**Pull request closed without merging**
