### PR TITLE
Fixed splash screen nonresponsive and improved background operation

### PR DESCRIPTION
**Pull request by wahibhaq**
#### Main changes:

- Ensure that those firebase warnings which are caused by wrong dataset and incomplete model specification are ignored
- New function introduced for fetching from firebase only once. This makes sense because this is startup launched and data is fetched to display only during SplashScreen 
- Refactored code to ensure there are no loose ends and better code readability 
- Realm onSuccess listener is used
- Introduced `Operation Completed` snackbar message for better UX and made progress bar invisible as soon as data is successfully received 

#### Warning

- I reviewed the other PR titled *Demo Release* and I can already see that there will be conflicts depending on which PR gets merged first. There are some overlapping changes.

#### Comments/Further Improvement:

- The reason why NGOs don't show database item is because the database has wrong key name which is `Address ` with a space and doesn't match with the field in model. Needs to be fixed on database level.
- Some chunk of delay on startup is contributed by `MainActivity` itself because it is doing a lot of operations in `onCreate()` aka Activity Creation Setup. This can be refactored and improved in future.

#### Suggestions for Merge:

- I screwed up a bit with commit history so kindly leave it to me for rebasing, squashing and merging it to master once I have a green signal to merge. 
- In future, I will work in the main repo directly instead of my forked repo.

### CODE REVIEW

**Comment by codernaut** [comment]
good to go from my end but let me first workout gitignore thing agree with changes and refactoring

**Comment by wahibhaq** [comment]
Ok cool. Just let me know

**Comment by codernaut** [comment]
have done the required changes yesterday as emailed please go ahead and merge

**Comment by codernaut** [comment]
or if you want me to do, i can also

**Comment by wahibhaq** [comment]
I don't think I can merge directly as there are conflicts expected. For now, just approve the PR and I will merge it myself.

**Pull request merged**
